name = "workers-ai-image-playground"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[ai]
binding = "AI"

[vars]
CLOUDFLARE_ACCOUNT_ID = "b98ff7eba201ab568a2cca72596285a2"